[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bascule = "EpjQWMXj6xgR2ijhJG1pmZpKmHM9is8vk8ATTfdVFtq7"
lbtc = "AZcLahWQE2kYFnM6VNhii4Fic3sCpv2RjSg6ekWYhXqS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
