use crate::{constants, errors::AssetRouterError, ID};

use anchor_lang::prelude::*;

use std::io::BufReader;
use std::result::Result as StdResult;

/// bytes4(keccak256("feeApproval(bytes32,bytes32,uint256,uint256)"))
pub const FEE_APPROVAL_ACTION: [u8; 4] = [0x04, 0xac, 0xbb, 0xb2];
pub const FEE_PAYLOAD_LEN: usize = 52;

#[derive(AnchorSerialize, AnchorDeserialize)]
/// A payload generated by the user for paying a fee associated with the `mint_with_fee`
/// instruction.
pub struct FeeAction {
    pub action: [u8; 4],
    pub chain_id: [u8; 16],
    pub verifying_contract: [u8; 16],
    pub fee: u64,
    pub expiry: u64,
}

impl FeeAction {
    pub fn from_bytes(bytes: &[u8]) -> StdResult<FeeAction, AssetRouterError> {
        let fee_action = Self::deserialize_reader(&mut BufReader::new(bytes))?;
        Ok(fee_action)
    }

    pub fn validate_fee(&self, max_fee: u64) -> StdResult<u64, AssetRouterError> {
        if self.action != FEE_APPROVAL_ACTION {
            return Err(AssetRouterError::InvalidFeeAction);
        }

        // in the fee permit payload we use only the first 16 bytes of the chain id
        // to keep tx size under the limit. Considering we use the genesis hash in Solana
        // Lombard Chain IDs, and the first byte selects the ecosystemthere is no risk
        // of collision.
        if self.chain_id != constants::CHAIN_ID[..16] {
            return Err(AssetRouterError::InvalidChainID);
        }

        // save space by using the first 16 bytes of the program id
        if self.verifying_contract != ID.to_bytes()[..16] {
            return Err(AssetRouterError::InvalidVerifyingcontract);
        }

        // Check expiry
        let clock = Clock::get()?;
        if clock.unix_timestamp as u64 > self.expiry {
            return Err(AssetRouterError::FeeApprovalExpired);
        }

        // Select correct fee
        Ok(std::cmp::min(self.fee, max_fee))
    }
}
