name: CI Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    if: github.event.pull_request.draft == false
    name: Unit tests
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release --all

  anchor-test:
    if: github.event.pull_request.draft == false
    name: Integration tests
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Anchor Test
        uses: metadaoproject/anchor-test@v2.2
        with:
          node-version: "20.11.0"
          solana-cli-version: "2.1.0"
          anchor-version: "0.31.1"

  fmt:
    if: github.event.pull_request.draft == false
    name: Fmt
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '18.17.0'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check formatting
        run: yarn lint
